### PR TITLE
Add tests for reading and setting variables.

### PR DESCRIPTION
**Pull request by jcrwilliams**
Adds a test suite for reading and setting variables in a simple C
program.

Refs #15 

Change-Id: If16867f4e358ca58cedde31c629cd8159842f28e
Signed-off-by: Jonathan Williams <jonwilliams@blackberry.com>

### CODE REVIEW

**Comment by jcrwilliams** [comment]
Not sure why it's saying I'm failing the ip-validation check. My ECA is up to date when I log in to eclipse.org

**Comment by simark** [comment]
Ohh thanks, I'll take a look.

> Not sure why it's saying I'm failing the ip-validation check. My ECA is up to date when I log in to eclipse.org

When I first contributed it did that I think.  I revoked and resigned it and it worked... (it was a more recent version of the ECA than what I had signed previously, that might explain it).

**Comment by jonahgraham** [comment]
@jcrwilliams the problem is your merge commit, it was done on github. Rebase your change and force push and that should solve it. Have a look at the link: https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5c003dec6b3b0

**Comment by jonahgraham** [comment]
PS your non-merge commit did pass validation, so your ECA is fine: https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5c003d637e4db

**Comment by simark** [comment]
> @jcrwilliams the problem is your merge commit, it was done on github. Rebase your change and force push and that should solve it. Have a look at the link: https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5c003dec6b3b0

@dschaefer, could we set the repo settings to forbid merge commits?

**Comment by simark** [comment]
@jcrwilliams I'm not able to leave review comments, Github tells me:

    Start commit oid is not part of the pull request

Could you rebase your branch on latest master and make sure there's no merge commit?

**Comment by jcrwilliams** [comment]
Closing this pull request and opening a new one.

**Comment by simark** [comment]
Ok.  It's also fine to force-push on your own branch to update an existing PR (IMO).

**Pull request closed without merging**
