### PR TITLE
Publish native sources

### PR DESCRIPTION
**Pull request by marechal-p**
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by marechal-p** [comment]
Because the sources for the native code are in src, we end up not publishing them.

Didn't know about this, my bad.

**Comment by dschaefer** [comment]
I don't think our tests test this so I'll just push it.

BTW, I'm still not comfortable publish sources up to npm. Not sure why consumers need it and if they do why npm or yarn links don't work for them.

I don't have a better strategy at the moment and will create a bug to discuss it later.

**Comment by marechal-p** [comment]
I only publish native sources, although there's a `src/integration-test/README.md` that also end up in the mix I don't know why.

The native code has to be build on the machines that depend on the adapter, I don't see how to not publish that.

**Comment by dschaefer** [comment]
> The native code has to be build on the machines that depend on the adapter, I don't see how to not publish that.

True. Still trying to get used to how that works with npm.

Though most clients I assume won't expect their users to run builds to install the adapter. At least that will be true for VS Code and Eclipse IDE. They will need to ship the binaries for all platforms.

**Comment by dschaefer** [comment]
Mind you, the native libraries are so sensitive to the version of node.js you're using it's going to take a different mind set to work.

**Comment by marechal-p** [comment]
> They will need to ship the binaries for all platforms.

Yes, still trying to wrap my head around that and how to properly do it. I wouldn't mind help with this, as I am not very familiar with the native world.

> Mind you, the native libraries are so sensitive to the version of node.js you're using it's going to take a different mind set to work.

Indeed, so far I thought that I used APIs simple enough that it wouldn't make a difference, hopefully. But maybe there are already caveats that I am just unaware of :/

**Pull request merged**
