### PR TITLE
Add tslint config file to get us started.

### PR DESCRIPTION
**Pull request by dschaefer**
Feel free to suggest changes here. This is just what we've been using for the last few months. I'm sure it could be made better.

### CODE REVIEW

**Comment by dschaefer** [comment]
Sure. I can take a look at that and update this.

**Comment by dschaefer** [comment]
I just grabbed the one from your change. Not seeing any warnings in vscode, but I'm not sure the check is running properly.

**Comment by simark** [comment]
> I just grabbed the one from your change. Not seeing any warnings in vscode, but I'm not sure the check is running properly.

Hmm I do:

ss

**Comment by dschaefer** [comment]
Ah, we didn't have tslint in the package.json file. See them now. I'll fix them all and resubmit.

**Comment by simark** [comment]
> Ah, we didn't have tslint in the package.json file. See them now. I'll fix them all and resubmit.

Ah, I probably had it as a leftover.

**Comment by dschaefer** [comment]
Yikes! Lots of little things but cleaned up nicely.

**Pull request merged**
